# Generated by Django 2.0.1 on 2018-02-04 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pythonmodels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What is the name of your dataset?', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to=pythonmodels.models.user_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('vars', models.IntegerField()),
                ('observations', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('nan', models.IntegerField()),
                ('mean', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('Q1', models.FloatField(blank=True, null=True)),
                ('median', models.FloatField(blank=True, null=True)),
                ('Q3', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('unique', models.IntegerField(blank=True, null=True)),
                ('top', models.TextField(blank=True, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
                ('first_date', models.DateTimeField(blank=True, null=True)),
                ('last_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonmodels.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='StatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonmodels.Dataset')),
            ],
        ),
    ]
