# Generated by Django 2.0 on 2017-12-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(help_text='What is the name of your dataset?', max_length=30),
        ),
    ]
