# Generated by Django 2.0 on 2017-12-12 03:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pythonmodels', '0003_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 12, 12, 3, 22, 13, 229165, tzinfo=utc))),
                ('updated_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 12, 12, 3, 22, 13, 229165, tzinfo=utc))),
                ('updated_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 3, 22, 13, 229165, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='statmodel',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonmodels.Dataset'),
        ),
        migrations.AddField(
            model_name='datasetvariable',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonmodels.Dataset'),
        ),
    ]
