# Generated by Django 2.0 on 2017-12-12 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pythonmodels', '0004_auto_20171211_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 16, 43, 46, 387975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datasetvariable',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 16, 43, 46, 388975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='statmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 16, 43, 46, 388975, tzinfo=utc)),
        ),
    ]
