# Generated by Django 2.0 on 2017-12-15 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pythonmodels', '0005_auto_20171212_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 5, 34, 41, 2523, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datasetvariable',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 5, 34, 41, 2523, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='statmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 5, 34, 41, 2523, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
