# Generated by Django 2.0 on 2017-12-15 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pythonmodels', '0006_auto_20171215_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 13, 35, 12, 344975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datasetvariable',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 13, 35, 12, 345975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='statmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 13, 35, 12, 346975, tzinfo=utc)),
        ),
    ]
